# This workflow carries out the build of the package with CMake

name: CMake build

on: [ push ]

jobs:
  build-GNU:
    runs-on: ubuntu-latest

    steps:
      # check out
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install gfortran libopenmpi-dev cmake

      - name: Run CMake builid
        run: |
          mkdir BUILD_GNU
          cd BUILD_GNU
          cmake ..
          make install

  build-Intel:
    runs-on: ubuntu-latest
    container:
      image: intel/oneapi-hpckit

    steps:
      # check out
      - uses: actions/checkout@v2

      - name: Run CMake builid
        run: |
          mkdir BUILD_Intel
          cd BUILD_Intel
          cmake ..
          make install
